apiVersion: v1
kind: Service
metadata:
  name: coupon-app-lb
spec:
  type: LoadBalancer
  ports:
  - port: 2426
    targetPort: 5002
  selector:
    app: coupon-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coupon-app
  template:
    metadata:
      labels:
        app: coupon-app
    spec:
      containers:
      - name: coupon-app
        image: matchbet-coupon
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: ConnectionString
          value: "host=postgres;port=5432;database=matchbet_db;username=my_user;password=pass1234"
